package com.mycompany.actividad1.gui;

/**
 *
 * @author noeli
 */
public class ConsultasVuelosDiarios extends javax.swing.JFrame {

    /**
     * Creates new form ConsultasVuelosiDarios
     */
    public ConsultasVuelosDiarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPanelSalidas = new javax.swing.JButton();
        btnPanelLlegadas = new javax.swing.JButton();
        btnVuelosCompaniaFecha = new javax.swing.JButton();
        btnVuelosDestino = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnRecaudaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 240, 248));

        btnPanelSalidas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPanelSalidas.setText("Panel de salidas");
        btnPanelSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelSalidasActionPerformed(evt);
            }
        });

        btnPanelLlegadas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPanelLlegadas.setText("Panel de llegadas");
        btnPanelLlegadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelLlegadasActionPerformed(evt);
            }
        });

        btnVuelosCompaniaFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVuelosCompaniaFecha.setText("Vuelos por compañía y fecha");
        btnVuelosCompaniaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuelosCompaniaFechaActionPerformed(evt);
            }
        });

        btnVuelosDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVuelosDestino.setText("Vuelos por destino");
        btnVuelosDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuelosDestinoActionPerformed(evt);
            }
        });

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homepage.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnRecaudaciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRecaudaciones.setText("Recaudaciones de vuelos");
        btnRecaudaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecaudacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecaudaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPanelSalidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPanelLlegadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVuelosDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVuelosCompaniaFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(btnMenu)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnPanelSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnPanelLlegadas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnVuelosCompaniaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnRecaudaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnVuelosDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenu)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanelSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelSalidasActionPerformed
        ConsultasSalidas consultasSalidas = new ConsultasSalidas();
        consultasSalidas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPanelSalidasActionPerformed

    private void btnPanelLlegadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelLlegadasActionPerformed
        ConsultasLlegadas consultasLlegadas = new ConsultasLlegadas();
        consultasLlegadas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPanelLlegadasActionPerformed

    private void btnVuelosCompaniaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuelosCompaniaFechaActionPerformed
        ConsultasVuelosCompanias consultasVuelosCompanias = new ConsultasVuelosCompanias();
        consultasVuelosCompanias.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVuelosCompaniaFechaActionPerformed

    private void btnVuelosDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuelosDestinoActionPerformed
        ConsultasVuelosSieteDias consultasVuelosSieteDias = new ConsultasVuelosSieteDias();
        consultasVuelosSieteDias.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVuelosDestinoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnRecaudacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecaudacionesActionPerformed
        ConsultasRecaudaciones consultasRecaudaciones = new ConsultasRecaudaciones();
        consultasRecaudaciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRecaudacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultasVuelosDiarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPanelLlegadas;
    private javax.swing.JButton btnPanelSalidas;
    private javax.swing.JButton btnRecaudaciones;
    private javax.swing.JButton btnVuelosCompaniaFecha;
    private javax.swing.JButton btnVuelosDestino;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
